/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_COUNTER2_PB_H_INCLUDED
#define PB_COUNTER2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Counter2 {
    int32_t left;
    int32_t right;
} Counter2;


/* Initializer values for message structs */
#define Counter2_init_default                    {0, 0}
#define Counter2_init_zero                       {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Counter2_left_tag                        1
#define Counter2_right_tag                       2

/* Struct field encoding specification for nanopb */
#define Counter2_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    left,              1) \
X(a, STATIC,   SINGULAR, INT32,    right,             2)
#define Counter2_CALLBACK NULL
#define Counter2_DEFAULT NULL

extern const pb_msgdesc_t Counter2_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Counter2_fields &Counter2_msg

/* Maximum encoded size of messages (where known) */
#define Counter2_size                            22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
