/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.2-dev */

#ifndef PB_PWM_CTRL_PB_H_INCLUDED
#define PB_PWM_CTRL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _PwmCtrl {
    int32_t channel;
    float duty;
} PwmCtrl;


/* Initializer values for message structs */
#define PwmCtrl_init_default                     {0, 0}
#define PwmCtrl_init_zero                        {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PwmCtrl_channel_tag                      1
#define PwmCtrl_duty_tag                         2

/* Struct field encoding specification for nanopb */
#define PwmCtrl_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    channel,           1) \
X(a, STATIC,   SINGULAR, FLOAT,    duty,              2)
#define PwmCtrl_CALLBACK NULL
#define PwmCtrl_DEFAULT NULL

extern const pb_msgdesc_t PwmCtrl_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PwmCtrl_fields &PwmCtrl_msg

/* Maximum encoded size of messages (where known) */
#define PwmCtrl_size                             16

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
