/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "Vector3.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Vector3, Vector3, AUTO)



